name: IntelliRack Web CI/CD

on:
  push:
    branches:
      - main
      - "release/**"
      - "hotfix/**"
      - "feature/**"
      - "v*" # For version tags
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      # - name: Run Lint & Tests
      #   run: |
      #     npm run lint
      #     npm test || echo "No tests found"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract git tag
        id: get_tag
        run: |
          echo "GIT_TAG=$(git describe --tags --abbrev=0 || echo latest)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/intellirack-web:latest
            ${{ secrets.DOCKER_USERNAME }}/intellirack-web:${{ env.GIT_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/intellirack-web:latest
          cache-to: type=inline
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NODE_ENV=production
            NEXT_PUBLIC_APP_NAME=IntelliRack
            NEXT_PUBLIC_APP_VERSION=${{ env.GIT_TAG }}

      # Optional: Upload build artifacts for debugging
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: .next
